"""update enum values and fix schema

Revision ID: 09b71a094e99
Revises: 5952423e99f3
Create Date: 2026-05-06 13:32:37.427754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09b71a094e99'
down_revision = '5952423e99f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.alter_column('diagnosis_notes',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('therapy_plans', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('Active', 'Completed', 'Cancelled', name='enumstatus'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('therapy_plans', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('Active', 'Completed', 'Cancelled', name='enumstatus'),
               nullable=False)

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.alter_column('diagnosis_notes',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
