"""add doctor notes appointments

Revision ID: 4d0a0f4eb7b2
Revises: 09b71a094e99
Create Date: 2026-05-13 23:03:57.793331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d0a0f4eb7b2'
down_revision = '09b71a094e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_notes',
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('exercise_feedback', schema=None) as batch_op:
        batch_op.alter_column('completion_status',
               existing_type=postgresql.ENUM('completed', 'partially_completed', 'skipped', name='enumcompletion'),
               nullable=True)

    with op.batch_alter_table('plan_exercises', schema=None) as batch_op:
        batch_op.alter_column('target_days',
               existing_type=postgresql.ENUM('sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', name='enumdays'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_exercises', schema=None) as batch_op:
        batch_op.alter_column('target_days',
               existing_type=postgresql.ENUM('sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', name='enumdays'),
               nullable=False)

    with op.batch_alter_table('exercise_feedback', schema=None) as batch_op:
        batch_op.alter_column('completion_status',
               existing_type=postgresql.ENUM('completed', 'partially_completed', 'skipped', name='enumcompletion'),
               nullable=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=False)

    op.drop_table('doctor_notes')
    # ### end Alembic commands ###
