"""add doctor_reply to feedback

Revision ID: fd0f10262af8
Revises: 4d0a0f4eb7b2
Create Date: 2026-05-19 02:46:29.108687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0f10262af8'
down_revision = '4d0a0f4eb7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_reply', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_feedback', schema=None) as batch_op:
        batch_op.drop_column('doctor_reply')

    # ### end Alembic commands ###
