"""
SendGridEmailClient
===================
Wraps the SendGrid Python SDK to send transactional emails on behalf of
the Mutabi platform.

Responsibilities
----------------
- Send a doctor invitation email containing a one-time activation token
  whenever an admin creates a new doctor account.
- The recipient uses the token to call POST /auth/set-password and activate
  their account within 24 hours.

Environment variables required
------------------------------
SENDGRID_API_KEY — API key obtained from the SendGrid dashboard.

Sender identity
---------------
All outgoing emails use the address defined in _FROM_EMAIL.  This address
must be verified as a Sender Identity in the SendGrid account before
emails can be delivered.

API reference
-------------
SendGrid Mail Send: POST https://api.sendgrid.com/v3/mail/send
Expected success status: 202 Accepted
"""

import os

from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

# Must be verified as a Sender Identity in the SendGrid account.
_FROM_EMAIL = "noreply@mutabi.sa"


class SendGridEmailClient:
    """SendGrid client for sending transactional emails."""

    def __init__(self):
        self._client = SendGridAPIClient(os.getenv("SENDGRID_API_KEY"))

    def send_doctor_invitation(self, to_email: str, doctor_name: str, token: str) -> None:
        """Send an account activation email to a newly created doctor.

        The email contains a one-time token that the doctor must submit to
        POST /auth/set-password within 24 hours to activate their account.

        Args:
            to_email:    Doctor's email address (must be unique in the system).
            doctor_name: Doctor's full name used for personalisation.
            token:       One-time invitation token generated by the admin service.

        Raises:
            RuntimeError: If SendGrid returns a status code other than 200 or 202.
        """
        message = Mail(
            from_email=_FROM_EMAIL,
            to_emails=to_email,
            subject="Welcome to Mutabi — Activate Your Account",
            plain_text_content=(
                f"Hello {doctor_name},\n\n"
                f"Your account has been created on the Mutabi platform.\n"
                f"Use the token below to set your password:\n\n"
                f"  {token}\n\n"
                f"This token expires in 24 hours. "
                f"If you did not request this, please contact your clinic admin.\n\n"
                f"Mutabi Team"
            ),
        )
        response = self._client.send(message)
        if response.status_code not in (200, 202):
            raise RuntimeError(f"SendGrid returned unexpected status {response.status_code}")
